# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "almalinux/8"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.56.2"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "libvirt" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
     vb.memory = "1024"
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  config.vm.hostname = "dns-backend"
  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "file", source: "../../shared_files/node_exporter.service", destination: "node_exporter.service"
  config.vm.provision "file", source: "../../shared_files/bind_exporter.service", destination: "bind_exporter.service"
  config.vm.provision "file", source: "../../shared_files/node_exporter-1.5.0.linux-amd64.tar.gz", destination: "node_exporter-1.5.0.linux-amd64.tar.gz"
  config.vm.provision "file", source: "../../shared_files/bind_exporter-0.6.1.linux-amd64.tar.gz", destination: "bind_exporter-0.6.1.linux-amd64.tar.gz"
  config.vm.provision "shell", inline: <<-SHELL
    yum update -y
    dnf install policycoreutils-python-utils net-tools wget -y
    semanage port -a -t dns_port_t -p udp 453
    semanage port -a -t dns_port_t -p tcp 8053
    useradd -rs /bin/false node_exporter
    groupadd --system prometheus
    useradd -s /sbin/nologin --system -g prometheus prometheus
    tar xvzf node_exporter*.tar.gz 
    tar xvzf bind_exporter*.tar.gz 
    cp /home/vagrant/node_exporter*/node_exporter /usr/local/bin
    cp /home/vagrant/bind_exporter*/bind_exporter /usr/local/bin
    cp /home/vagrant/*_exporter.service /lib/systemd/system
    restorecon -Rv /usr/local/bin
    systemctl daemon-reload
    systemctl enable node_exporter
    systemctl start node_exporter.service 
    systemctl enable bind_exporter
    systemctl start bind_exporter.service 
  SHELL
end
