---
# tasks file for Bind setup
- name: Configure repo isc-bind
  command: "dnf copr enable -y isc/bind"

- name: Install isc-bind
  yum:
    pkg: isc-bind
    state: present

- name: Configure isc-bind service
  systemd:
    state: started
    enabled: true
    name: isc-bind-named

- name: Set hostname
  hostname:
    name: "{{ host_name }}"
    use: 'systemd'

- name: Set hostname fact
  set_fact:
    ansible_fqdn: "{{ host_name }}"

- name: SE Linux configuration for DoH
  seboolean:
    name: named_tcp_bind_http_port
    state: yes
    persistent: yes

- name: Allow named access to certificate
  tags: bind9-fixCert
  file:
    path: "/etc/pki/tls/private/rsx218-dox.key"
    owner: root
    group: named
    mode: '640'

- name: Copy named conf file
  tags: bind9-update
  template:
    src: named.conf.j2
    dest: /etc/opt/isc/scls/isc-bind/named.conf
    owner: root
    group: named
    mode: 0660
  notify: restart named
