---
# tasks file for Bind setup
- name: 'create serial based on actual timestamp'
  tags: bind9-update
  command: date +%m%d%H%M%S
  register: timestamp
  check_mode: false
  run_once: true

- name: Configure repo isc-bind
  command: "dnf copr enable -y isc/bind"

- name: Install isc-bind
  yum:
    pkg: isc-bind
    state: present

- name: Configure isc-bind service
  systemd:
    state: started
    enabled: true
    name: isc-bind-named

- name: Set hostname
  hostname:
    name: "{{ host_name }}"
    use: 'systemd'

- name: Set hostname fact
  set_fact:
    ansible_fqdn: "{{ host_name }}"

- name: Copy named conf file
  tags: bind9-update
  template:
    src: named.conf.j2
    dest: /etc/opt/isc/scls/isc-bind/named.conf
    owner: root
    group: named
    mode: 0660
  notify: restart named

- name: Make named directory
  file:
    path: /etc/opt/isc/scls/isc-bind/named
    state: directory
    owner: root
    group: named
    mode: 0750

- name: Copy named conf local file
  tags: bind9-update
  template:
    src: named.conf.local.j2
    dest: /etc/opt/isc/scls/isc-bind/named/named.conf.local
    owner: root
    group: named
    mode: 0640
  notify: restart named


- name: Make zones Directory
  file:
    path: /etc/opt/isc/scls/isc-bind/named/zones
    state: directory
    owner: root
    group: named
    mode: 0750

- name: Copy forward file
  tags: bind9-update
  template:
    src: db.forward.j2
    dest: "/etc/opt/isc/scls/isc-bind/named/zones/db.{{ domain }}"
    owner: root
    group: named
    mode: 0640
  notify: restart named


- name: Copy reverse file
  tags: bind9-update
  template:
    src: db.reverse.j2
    dest: "/etc/opt/isc/scls/isc-bind/named/zones/db.{{ rev_domain }}"
    owner: root
    group: named
    mode: 0640
  notify: restart named
